/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardImportRouteImport } from './routes/dashboard/import'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard/discover'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardItemsIndexRouteImport } from './routes/dashboard/items/index'
import { Route as DashboardItemsItemIdRouteImport } from './routes/dashboard/items/$itemId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSummaryRouteImport } from './routes/api/ai/summary'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardItemsIndexRoute = DashboardItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardItemsItemIdRoute = DashboardItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSummaryRoute = ApiAiSummaryRouteImport.update({
  id: '/api/ai/summary',
  path: '/api/ai/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/dashboard/items': typeof DashboardItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/dashboard/items/$itemId'
    | '/dashboard/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/dashboard/items/$itemId'
    | '/dashboard/items'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/dashboard/items/$itemId'
    | '/dashboard/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAiSummaryRoute: typeof ApiAiSummaryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/items/': {
      id: '/dashboard/items/'
      path: '/items'
      fullPath: '/dashboard/items/'
      preLoaderRoute: typeof DashboardItemsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/items/$itemId': {
      id: '/dashboard/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/dashboard/items/$itemId'
      preLoaderRoute: typeof DashboardItemsItemIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/summary': {
      id: '/api/ai/summary'
      path: '/api/ai/summary'
      fullPath: '/api/ai/summary'
      preLoaderRoute: typeof ApiAiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardItemsItemIdRoute: typeof DashboardItemsItemIdRoute
  DashboardItemsIndexRoute: typeof DashboardItemsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardItemsItemIdRoute: DashboardItemsItemIdRoute,
  DashboardItemsIndexRoute: DashboardItemsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAiSummaryRoute: ApiAiSummaryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
